# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ple <- function(x, d) {
    .Call('rucl_ple', PACKAGE = 'rucl', x, d)
}

BSmean <- function(x, N) {
    .Call('rucl_BSmean', PACKAGE = 'rucl', x, N)
}

BSple <- function(x, d, N) {
    .Call('rucl_BSple', PACKAGE = 'rucl', x, d, N)
}

